title: Guillaume Braun
position: Postdoctoral Researcher
affiliation: Riken AIP - Tokyo
email: guillaume.braun@riken.jp
google_scholar: https://scholar.google.com/citations?user=lzebyjAAAAAJ&hl=fr
github_link: https://github.com/glmbraun
avatar: ./assets/img/prof2b.jpg
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
remote_theme: yaoyao-liu/minimal-light
